### PR TITLE
refactor/models

### PR DESCRIPTION
**Pull request by naftalima**
## Objective and Motivation
- Refactor the models so that it is easier to understand and maintain.

### Entity-Relationship Diagram:
image

### CODE REVIEW

**Comment by naftalima** [comment]
### I don't know why it is failing 
image
Circle CI

### I tried to redo it locally and everything passed
image

**Comment by rsarai** [comment]
@naftalima Duda had the same issue on her project and she was able to fix it. I will ask you to sync with her.
It may be a version problem.

**Review by rsarai — CHANGES_REQUESTED** [review]
The code looks good, but the build is breaking.

**Comment by naftalima** [comment]
Yes, I was on the call with her when she solved this problem. 
I tried the same thing, which is to run:
```$ pre-commit run --all-files```
as you can see in the previous comment, everything passed locally.

**Comment by rsarai** [comment]
@naftalima please check for differences on versions of `black` running on your CI and on your local machine. I suggest you to run the `black` command locally after this version check

**Pull request merged**
