### PR TITLE
Feat/async battle

### PR DESCRIPTION
**Pull request by naftalima**
## Objective and Motivation
- run battles asyncronously

### CODE REVIEW

**Comment by rsarai** [comment]
Let me know when this is tested so I can approve it

**Comment by naftalima** [comment]
is working locally.
image

**Comment by naftalima** [comment]
image

image

**Comment by naftalima** [comment]
On heroku it has `REDIS_TLS_URL` and `REDIS_URL` keys

**Review by rsarai — APPROVED** [review]

**Pull request merged**
